name: Build Docker Compose

on:
  push:
    branches: [master]
  workflow_dispatch:  

permissions:
  contents: read
  packages: write    

jobs:
  download_betterfront_docker_image:
    runs-on: ubuntu-latest

    steps:
      - name: Download BetterFront Docker artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{ secrets.GH_PAT }}   # must have repo access
          repo: ${{ github.repository }}        # same repo
          workflow: cache-betterfront-image.yml              
          name: betterfront-docker-image        
          path: ./downloaded                           

      - name: Load Docker image
        run: docker load -i ./downloaded/betterfront-latest.tar

      - name: Verify Docker image exists
        run: |
          docker images --format '{{.Repository}}:{{.Tag}}' | grep -q '^betterfront:latest$' \
          && echo "Image found ✅" \
          || (echo "Image NOT found ❌" && exit 1)
  
       
